CREATE TABLE [dbo].Org
(
	OrgIdPk INT NOT NULL PRIMARY KEY,
	OrgCode VARCHAR(50) NOT NULL,
	OrgName VARCHAR(255) NOT NULL,
	AddressLine1 VARCHAR(255) NULL,
	AddressLine2 VARCHAR(255) NULL,
	City VARCHAR(100) NULL,
	State VARCHAR(100) NULL,
	ZipCode VARCHAR(20) NULL,
)
