CREATE TABLE [dbo].Org
(
	OrgIdPk				INT NOT NULL PRIMARY KEY,
	OrgCode				VARCHAR(50)  NOT NULL,
	OrgName				VARCHAR(255) NOT NULL,
	RegistrationNumber	VARCHAR(128) NULL,
	AddressLine1		VARCHAR(256) NULL,
	AddressLine2		VARCHAR(255) NULL,
	City				VARCHAR(100) NULL,
	[State]				VARCHAR(100) NULL,
	ZipCode				VARCHAR(20)  NULL,
	CreatedBy			VARCHAR(512) NOT NULL,
	CreatedOn			DATETIME NOT NULL DEFAULT(GETDATE()),
	LastUpdatedBy		VARCHAR(512) NOT NULL,
	LastUpdatedOn		DATETIME NOT NULL
)
